version: '3.8'

services:
  go-content:
    image: go-content:latest
    container_name: go-content
    hostname: go-content
    restart: unless-stopped
    ports:
      - "8114:8080"

    restart: unless-stopped
